language: node_js
node_js:
- "stable"
services:
  - postgresql
 before_script:
  - createuser gbenga -s -U postgres
  - createdb postit --username=gbenga
  - sequelize db:migrate
after_success:
- npm run cover
after_script: 
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
