language: node_js
node_js:
- "stable"
services:
  - postgresql
before_script:
  - npm install sequelize-cli -g
  - export DEV_DB=postgres://lgitfcgq:1T6i6xAB6KW9fC-D4AsRgq5qlcDQA-VU@stampy.db.elephantsql.com:5432/lgitfcgq
after_success:
- npm run cover
after_script: 
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
env:
  -TOKEN_SECRET =travis-secret