language: node_js
node_js:
- "stable"
services:
  - postgresql
before_script:
  - npm install sequelize-cli -g
  - psql -c 'create database postit;' -U postgres
  - sequelize db:migrate
after_success:
- npm run cover
after_script: 
  - nyc npm test && nyc report --reporter=text-lcov | coveralls